### PR TITLE
Add clickable document card and show document on the right

### PR DESCRIPTION
**Pull request by leetdavid**
This pull request adds functionality to make the document card clickable and display the corresponding document on the right side of the screen.

### CODE REVIEW

**Comment by betamax** [comment]
I was thinking of changing this a bit to work using the URL parameters, so if there is a doc there is `doc=ID` in the URL and then if we detect it in the URL then it shows the document, and I think then should also async load the document from ES using a query by ID, if it doesn't have the source from the results. What do you think?

**Comment by leetdavid** [comment]
That makes sense. Feel free to take the wheel on this one :)

**Comment by betamax** [comment]
@leetdavid okay, I think it's ready now! I added in the expanded view, cycling between docs and some other bits. I'm going to look at pagination now on a branch off of this one.

**Comment by leetdavid** [comment]
LGTM! Nice!

**Pull request merged**
